import Link from "next/link";
import { getAllServices } from "@/lib/services";
import { LOCATIONS, getRegions, getLocationsByRegion } from "@/lib/locations";
import { getAllPosts } from "@/lib/blog";

const MAIN_PAGES = [
  { label: "Home", href: "/" },
  { label: "About", href: "/about" },
  { label: "Our Team", href: "/our-team" },
  { label: "Services", href: "/services" },
  { label: "Areas We Serve", href: "/areas-we-serve" },
  { label: "Blog", href: "/blog" },
  { label: "Appointments", href: "/appointments" },
  { label: "Contact Us", href: "/contact-us" },
  { label: "Privacy Policy", href: "/privacy-policy" },
] as const;

/**
 * Human-readable HTML sitemap at /sitemap (distinct from the machine
 * /sitemap.xml generated by app/sitemap.ts). Lists every page on the site,
 * including all 451 "Areas We Serve" pSEO pages (1 hub + 30 city + 420
 * city x service combo pages), grouped by region/city in accordions so the
 * page stays scannable.
 */
export function SitemapView() {
  const services = getAllServices();
  const posts = getAllPosts();
  const regions = getRegions();
  const comboCount = LOCATIONS.length * services.length;
  const totalPages =
    MAIN_PAGES.length + services.length + 1 + LOCATIONS.length + comboCount + posts.length;

  return (
    <>
      {/* ---------- Hero ---------- */}
      <section className="relative w-full overflow-hidden bg-espresso py-24 md:py-32">
        <div
          aria-hidden="true"
          className="pointer-events-none absolute inset-0"
          style={{
            background:
              "radial-gradient(55% 60% at 85% 0%, rgba(185,165,144,0.16) 0%, rgba(54,48,42,0) 60%), radial-gradient(45% 55% at 10% 100%, rgba(87,76,63,0.4) 0%, rgba(54,48,42,0) 55%)",
          }}
        />
        <div className="container-shell relative z-10">
          <div className="flex items-center gap-3">
            <span aria-hidden="true" className="block h-px w-10 bg-tan/60" />
            <p className="eyebrow">Sitemap</p>
          </div>
          <h1 className="mt-4 max-w-3xl font-serif text-4xl leading-[1.05] tracking-tight text-linen md:text-5xl lg:text-6xl">
            Every page on{" "}
            <span className="italic text-tan">Aligned Health.</span>
          </h1>
          <p className="mt-6 max-w-xl text-base leading-relaxed text-linen/85 md:text-lg">
            A complete, human-readable index of the site &mdash; {totalPages}{" "}
            pages in total, including our services, blog, and every Orange
            County city and neighborhood we serve.
          </p>
        </div>
      </section>

      {/* ---------- Main pages ---------- */}
      <section className="section-cream section relative overflow-hidden">
        <div className="container-shell relative z-10">
          <p className="eyebrow">Main pages</p>
          <h2 className="heading-section mt-4">Start here.</h2>
          <span className="divider-hairline mt-8 block" />
          <ul className="mt-8 grid grid-cols-2 gap-3 md:grid-cols-3 md:gap-4 lg:grid-cols-4">
            {MAIN_PAGES.map((page) => (
              <SitemapLink key={page.href} href={page.href} label={page.label} />
            ))}
          </ul>
        </div>
      </section>

      {/* ---------- Services ---------- */}
      <section className="section-linen section relative overflow-hidden">
        <div className="container-shell relative z-10">
          <p className="eyebrow">Services</p>
          <h2 className="heading-section mt-4">
            {services.length}{" "}
            <span className="italic text-tan">services</span> we offer.
          </h2>
          <span className="divider-hairline mt-8 block" />
          <ul className="mt-8 grid grid-cols-2 gap-3 md:grid-cols-3 md:gap-4 lg:grid-cols-4">
            {services.map((service) => (
              <SitemapLink
                key={service.slug}
                href={`/services/${service.slug}`}
                label={service.label}
              />
            ))}
          </ul>
        </div>
      </section>

      {/* ---------- Areas we serve (pSEO pages) ---------- */}
      <section className="section-cream section relative overflow-hidden">
        <div className="container-shell relative z-10">
          <p className="eyebrow">Areas we serve</p>
          <h2 className="heading-section mt-4">
            {LOCATIONS.length}{" "}
            <span className="italic text-tan">Orange County cities,</span>{" "}
            every service.
          </h2>
          <span className="divider-hairline mt-8 block" />
          <ul className="mt-8 grid grid-cols-2 gap-3 md:grid-cols-3 md:gap-4 lg:grid-cols-4">
            <SitemapLink href="/areas-we-serve" label="Areas We Serve (hub)" />
          </ul>

          <div className="mt-10 divide-y divide-tan/15 rounded-3xl border border-tan/20 bg-cream">
            {regions.map((region) => (
              <RegionAccordion
                key={region}
                region={region}
                cities={getLocationsByRegion(region)}
                services={services}
              />
            ))}
          </div>
        </div>
      </section>

      {/* ---------- Blog ---------- */}
      <section className="section-linen section relative overflow-hidden">
        <div className="container-shell relative z-10">
          <p className="eyebrow">From the journal</p>
          <h2 className="heading-section mt-4">
            {posts.length}{" "}
            <span className="italic text-tan">blog posts.</span>
          </h2>
          <span className="divider-hairline mt-8 block" />
          <ul className="mt-8 grid grid-cols-1 gap-3 md:grid-cols-2 lg:grid-cols-3">
            {posts.map((post) => (
              <SitemapLink
                key={post.slug}
                href={`/blog/${post.slug}`}
                label={post.title}
              />
            ))}
          </ul>
        </div>
      </section>
    </>
  );
}

/* ---------------------------------------------------------------------- */

function SitemapLink({ href, label }: { href: string; label: string }) {
  return (
    <li>
      <Link
        href={href}
        className="group relative block overflow-hidden rounded-2xl border border-tan/25 bg-cream p-4 text-sm leading-snug text-espresso transition-colors hover:border-tan/50 hover:text-tan md:p-5"
      >
        {label}
      </Link>
    </li>
  );
}

function RegionAccordion({
  region,
  cities,
  services,
}: {
  region: string;
  cities: readonly { slug: string; name: string }[];
  services: readonly { slug: string; label: string }[];
}) {
  return (
    <details className="group p-6 md:p-7">
      <summary className="flex cursor-pointer list-none items-center justify-between gap-4 font-serif text-lg text-espresso md:text-xl">
        {region}
        <span
          aria-hidden="true"
          className="shrink-0 text-tan transition-transform group-open:rotate-45"
        >
          +
        </span>
      </summary>
      <div className="mt-4 divide-y divide-tan/10">
        {cities.map((city) => (
          <CityAccordion key={city.slug} city={city} services={services} />
        ))}
      </div>
    </details>
  );
}

function CityAccordion({
  city,
  services,
}: {
  city: { slug: string; name: string };
  services: readonly { slug: string; label: string }[];
}) {
  return (
    <details className="group py-4 first:pt-0 last:pb-0">
      <summary className="flex cursor-pointer list-none items-center justify-between gap-4 text-sm font-medium text-espresso md:text-base">
        <Link href={`/areas-we-serve/${city.slug}`} className="hover:text-tan">
          {city.name}
        </Link>
        <span
          aria-hidden="true"
          className="shrink-0 text-tan transition-transform group-open:rotate-45"
        >
          +
        </span>
      </summary>
      <ul className="mt-3 grid grid-cols-2 gap-2 md:grid-cols-3 lg:grid-cols-4">
        {services.map((service) => (
          <li key={service.slug}>
            <Link
              href={`/areas-we-serve/${city.slug}/${service.slug}`}
              className="block truncate text-xs leading-relaxed text-mocha transition-colors hover:text-tan"
            >
              {service.label}
            </Link>
          </li>
        ))}
      </ul>
    </details>
  );
}
